<?php

$mid = 'PAYZON-3710205';
$pw = 'Payzone123';
$presharedkey='PreSharedKey';
//$amt = '1234';
//$orderid = '1234';
$transactiontype='SALE';// PREAUTH COLLECTION REFUND
$currencycode = '826';
$transactiondatetime = date('Y-m-d H:i:s P');
$orderdesc= 'Order description ';
//$customername= 'Geoff Wayne';
//$address1= '113 Broad Street West';
//$address2= 'Old pine';
//$address3= 'Strongbarrow';
$address4= 'AddFour';
$city= 'City';
$state= 'State';
//$postcode= 'SB42 1SX';
$countrycode= '826';
$hashmethod= 'SHA1';
$callbackurl= 'http://127.0.0.1/PHP_shopping_cart/misc/place_order.php';
$echoavs= 'true';
$echocv2= 'true';
$echothreed= 'true';
$echocardtype= 'true';
$echocardtype= 'true';
$cv2mandatory= 'true';
$address1mandatory= 'true';
$citymandatory= 'true';
$postcodemandatory= 'true';
$statemandatory= 'true';
$countrymandatory= 'true';
$resultdeliverymethod= 'POST';
$serverresulturl= '';
$paymentformsdisplaysresult= 'true';
$serverresulturlcookievariables= '';
$serverresulturlformvariables= '';
$serverresulturlquerystringvariables= '';